### ISSUE TITLE
tf1 image incompatible with latest armory changes

### ISSUE THREAD

**Issue by lcadalzo** [twosixlabs/armory#1358]
The changes introduced in #1341 make armory incompatible with the tf1 image since the `list_physical_devices()` can't be called:

```
I have no name!@a6fb1874117c:/workspace$ python -m armory.scenarios.main /armory/tmp/2022-03-23T150956.294738/interactive-config.json --check
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/conda/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/workspace/armory/__init__.py", line 77, in <module>
    gpus = tf.config.list_physical_devices("GPU")
  File "/opt/conda/lib/python3.7/site-packages/tensorflow_core/python/util/module_wrapper.py", line 193, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'tensorflow._api.v1.config' has no attribute 'list_physical_devices'
```

I suppose one option could be to add logic to `__init__.py` that checks the tf version, then only sets tf memory growth if the version is tf2.

Another could be to simply deprecate the tf1 image and say if you want to use tf1, you must use Armory < 0.15.0. If we want to go this route, we still might want a more informative error message than the above

**Comment by davidslater** [comment]
We are definitely deprecating TF1, but a user-facing error would be helpful.
